<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/backend/">Trang Chủ</a></li>
    <li class="breadcrumb-item"><a href="/backend/banner">Banner</a></li>
    <li class="breadcrumb-item active">Tạo mới</li>
</ol>
<section class="content">
    <div class="card card-primary ">
        <div class="card-header">
            <h4 class="card-title">
                Thêm Banner
            </h4>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="card-body">
                <?php

                use Model\Banner\BannerForm;

                $formTable = new BannerForm();
                // $formTable->Id()->render();
                ?>
                <div class="">
                    <div class="col-6">
                        <?php $formTable->Name()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->UrlImages()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->STT()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->Link()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->GroupName()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->Description()->renderHtml();  ?>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-success">Thêm</button>
            </div>
        </form>
    </div>

</section>