 <section class="content-header">
     <div class="container-fluid">
         <div class="row mb-2">
             <div class="col-sm-6">
                 <h1>Thêm Tài khoản</h1>
             </div>
             <div class="col-sm-6">
                 <ol class="breadcrumb float-sm-right">
                     <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                     <li class="breadcrumb-item "><a href="/backend/admin">Quản Lý Tài khoản</a></li>
                     <li class="breadcrumb-item active">Tạo Mới</li>

 </section>

 <!-- Main content -->
 <section class="content">
     <!-- Default box -->
     <form action="" method="POST">
         <div class="card">
             <div class="card-header">
                 <h3 class="card-title">Thông tin cá nhân</h3>
                 <div class="card-tools">
                     <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                         <i class="fas fa-minus"></i>
                     </button>
                     <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                         <i class="fas fa-times"></i>
                     </button>
                 </div>
             </div>
             <div class="card-body">
                 <div class="row">
                     <div class="col-6">
                         <div class="form-group">
                             <label for="">Họ & Tên</label>
                             <input type="text" name="user[HoTen]" class="form-control" placeholder="Họ & Tên" aria-describedby="helpId">
                         </div>
                         <div class="form-group">
                             <label for="">SĐT</label>
                             <input type="text" name="user[SDT]" class="form-control" placeholder="SĐT" aria-describedby="helpId">
                         </div>
                         <div class="form-group">
                             <label for="">Email</label>
                             <input type="text" name="user[Email]" class="form-control" placeholder="Email" aria-describedby="helpId">
                         </div>
                     </div>
                     <div class="col-6">
                         <div class="form-group">
                             <label for="">Tài Khoản</label>
                             <input type="text" name="user[TaiKhoan]" class="form-control" placeholder="SĐT" aria-describedby="helpId">
                         </div>
                         <div class="form-group">
                             <label for="">Mật Khẩu</label>
                             <input type="password" name="user[MatKhau]" class="form-control" placeholder="Email" aria-describedby="helpId">
                         </div>
                     </div>
                 </div>
                 <div class="form-group">
                     <label for="">Địa Chỉ</label>
                     <input type="text" name="user[DiaChi]" class="form-control" placeholder="Địa Chỉ" aria-describedby="helpId">
                 </div>
                 <div class="row">
                     <div class="col-4 form-group">
                         <label for="">Tỉnh</label>
                         <select id="tinhThanh" name="user[Tinh]" class="form-control"> </select>
                     </div>
                     <div class="col-4 form-group">
                         <label for="">Huyện</label>
                         <select id="quanHuyen" name="user[Huyen]" class="form-control"> </select>

                     </div>
                     <div class="col-4 form-group">
                         <label for="">Xã</label>
                         <select id="phuongXa" name="user[Xa]" class="form-control"> </select>
                     </div>
                 </div>

             </div>
             <!-- /.card-body -->
             <div class="card-footer">
                 <!-- Footer -->
                 <button name="btnLuu" class="btn btn-success">
                     Lưu
                 </button>
                 <button type="reset" class="btn btn-default">
                     Làm lại
                 </button>
             </div>
             <!-- /.card-footer-->
         </div>
     </form>
 </section>
 <!-- /.content -->
 <script src="/public/TinhThanh/tinhthanh.js"></script>