 <?php

    use Model\Admin;

    $admin = new Admin($data["Id"]);
    ?>


 <section class="content-header">
     <div class="container-fluid">
         <div class="row mb-2">
             <div class="col-sm-6">
                 <h1>Cấp Lại Mật Khẩu</h1>
             </div>
             <div class="col-sm-6">
                 <ol class="breadcrumb float-sm-right">
                     <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                     <li class="breadcrumb-item "><a href="/backend/admin">Quản Lý Tài khoản</a></li>
                     <li class="breadcrumb-item active">Sửa</li>

 </section>

 <!-- Main content -->
 <section class="content">
     <!-- Default box -->
     <form action="" method="POST">
         <div class="card">
             <div class="card-header">
                 <h3 class="card-title">Bảo Mật</h3>
                 <div class="card-tools">
                     <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                         <i class="fas fa-minus"></i>
                     </button>
                     <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                         <i class="fas fa-times"></i>
                     </button>
                 </div>
             </div>
             <div class="card-body">
                 <div class="row">
                     <div class="col-6">
                         <div class="form-group">
                             <label for="">Mật Khẩu Mới</label>
                             <input value="<?php echo $admin->Id; ?>" type="hidden" name="user[Id]">
                             <input autocomplete="off" type="password" name="user[Password]" class="form-control" aria-describedby="helpId">
                         </div>
                         <div class="form-group">
                             <label for="">Nhập Lại Mật Khẩu Mới</label>
                             <input autocomplete="off" type="password" name="user[NewPassword]" class="form-control" aria-describedby="helpId">
                         </div>
                     </div>
                 </div>
             </div>
             <div class="card-footer">
                 <button name="btnLuu" class="btn btn-success">
                     Lưu
                 </button>
                 <button type="reset" class="btn btn-default">
                     Làm lại
                 </button>
             </div>
         </div>
     </form>
 </section>