<?php

use Model\DanhMuc;
use Model\GioHang;
use Model\SanPham;

$sanPham = new SanPham();
$danhSachSanPham = $sanPham->GetFeaturesItems(12);
?>

<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Features Items</h2>
    <?php
    if ($danhSachSanPham) {
        while ($row = $danhSachSanPham->fetch_assoc()) {
            $_item = new SanPham($row);
    ?>
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img onerror="this.src='/public/no-image.jpg'" src="<?php echo $_item->UrlImages; ?>" alt="<?php echo $_item->Name; ?>" />
                            <h2><?php echo $_item->Price(); ?></h2>
                            <p><?php echo $_item->Name; ?></p>
                            <a href="<?php echo GioHang::linkThemGioHang($_item->Id); ?>" class="btn btn-default add-to-cart">
                                <i class="fa fa-shopping-cart"></i>
                                Thêm vào giỏ hàng
                            </a>
                        </div>
                        <div class="product-overlay">
                            <div class="overlay-content">
                                <h2><?php echo $_item->Price(); ?></h2>
                                <p><?php echo $_item->Name; ?></p>
                                <a href="<?php echo GioHang::linkThemGioHang($_item->Id); ?>" class="btn btn-default add-to-cart">
                                    <i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</a>
                            </div>
                        </div>
                    </div>
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified">
                            <li>
                                <a href="#"><i class="fa fa-plus-square"></i>Yêu Thích</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-plus-square"></i>So Sánh</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

    <?php
        }
    }

    ?>
</div>
<!--features_items-->

<div class="category-tab">
    <!--category-tab-->
    <div class="col-sm-12">
        <ul class="nav nav-tabs">
            <?php
            $danhMuc = new DanhMuc();
            $total = 0;
            $danhSachDanhMuc =
                $danhMuc->GetPaging([], 1, 6, $total);
            $index = 0;
            if ($danhSachDanhMuc) {
                while ($row = $danhSachDanhMuc->fetch_assoc()) {
                    $_item = new DanhMuc($row);
            ?>
                    <li class="<?php echo $index++ == 0 ? 'active' : '' ?>">
                        <a href="#tabs<?php echo $_item->Id ?>" data-toggle="tab">
                            <?php echo $_item->Name; ?>
                        </a>
                    </li>
            <?php
                }
            }
            ?>
        </ul>
    </div>
    <div class="tab-content">
        <?php
        $danhMuc = new DanhMuc();
        $total = 0;
        $danhSachDanhMuc =
            $danhMuc->GetPaging([], 1, 6, $total);
        $index = 0;
        if ($danhSachDanhMuc) {
            while ($row = $danhSachDanhMuc->fetch_assoc()) {
                $_item = new DanhMuc($row);
                $danhSachSanPham = $_item->GetSanPhams(4);
        ?>
                <div class="tab-pane fade   <?php echo $index++ == 0 ? 'active' : '' ?>  in" id="tabs<?php echo $_item->Id ?>">
                    <?php
                    if ($danhSachSanPham) {
                        while ($row1 = $danhSachSanPham->fetch_assoc()) {
                            $_item1 = new SanPham($row1);
                    ?>
                            <div class="col-sm-3">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            <img onerror="this.src='/public/no-image.jpg'" src="<?php echo $_item1->UrlImages; ?>" alt="<?php echo $_item1->Name; ?>" />
                                            <h2><?php echo $_item1->Price(); ?></h2>
                                            <p><?php echo $_item1->Name; ?></p>
                                            <a href="<?php echo GioHang::linkThemGioHang($_item1->Id); ?>" class="btn btn-default add-to-cart">
                                                <i class="fa fa-shopping-cart"></i>Thêm giỏ hàng
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                    <?php
                        }
                    }
                    ?>
                </div>
        <?php
            }
        }
        ?>



    </div>
</div>
<!--/category-tab-->

<div class="recommended_items">
    <!--recommended_items-->
    <h2 class="title text-center">recommended items</h2>

    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img src="/public/Eshopper/images/home/recommend1.jpg" alt="" />
                                <h2>$56</h2>
                                <p>Easy Polo Black Edition</p>
                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img src="/public/Eshopper/images/home/recommend2.jpg" alt="" />
                                <h2>$56</h2>
                                <p>Easy Polo Black Edition</p>
                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img src="/public/Eshopper/images/home/recommend3.jpg" alt="" />
                                <h2>$56</h2>
                                <p>Easy Polo Black Edition</p>
                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img src="/public/Eshopper/images/home/recommend1.jpg" alt="" />
                                <h2>$56</h2>
                                <p>Easy Polo Black Edition</p>
                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img src="/public/Eshopper/images/home/recommend2.jpg" alt="" />
                                <h2>$56</h2>
                                <p>Easy Polo Black Edition</p>
                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img src="/public/Eshopper/images/home/recommend3.jpg" alt="" />
                                <h2>$56</h2>
                                <p>Easy Polo Black Edition</p>
                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</div>
<!--/recommended_items-->