<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="/">Trang Chủ</a></li>
                <li class="active">Giỏ Hàng</li>
            </ol>
        </div>
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Sản phẩm</td>
                        <td class="description"></td>
                        <td class="price">Giá</td>
                        <td class="quantity">Số lượng</td>
                        <td class="total">Thành tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    <?php

                    use Model\Common;
                    use Model\GioHang;
                    use Model\SanPham;

                    $gioHang = new GioHang();
                    $DanhSachSanPham = $gioHang->DanhSachSanPham();
                    foreach ($DanhSachSanPham as $maSanPham => $sanpham) {
                        $_item = new SanPham($sanpham);
                    ?>
                        <tr>
                            <td class="cart_product" style="margin: 0px;">
                                <a href=""><img onerror="handleError(this);" style="height: 100px;" src="<?php echo $_item->UrlImages; ?>" alt="<?php echo $_item->Name ?>" /></a>
                            </td>
                            <td class="cart_description">
                                <h4><a href=""><?php echo $_item->Name ?></a></h4>
                                <p>Web ID: <?php echo $_item->Id ?></p>
                            </td>
                            <td class="cart_price">
                                <p><?php echo $_item->Price() ?></p>
                            </td>
                            <td class="cart_quantity">
                                <div class="cart_quantity_button">
                                    <a class="cart_quantity_up" href="<?php echo GioHang::LinkThemSoLuong($_item->Id); ?>"> + </a>
                                    <input class="cart_quantity_input" type="text" name="quantity" value="<?php echo $_item->number ?>" autocomplete="off" size="2" />
                                    <a class="cart_quantity_down" href="<?php echo GioHang::LinkGiamSoLuong($_item->Id); ?>"> - </a>
                                </div>
                            </td>
                            <td class="cart_total">
                                <p class="cart_total_price"><?php echo $_item->ThanhTienView() ?></p>
                            </td>
                            <td class="cart_delete">
                                <a class="cart_quantity_delete" href="<?php echo GioHang::LinkXoaSanPham($_item->Id); ?>"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>

                    <?php
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</section>
<!--/#cart_items-->

<section id="do_action">
    <div class="container">
        <div class="heading">
            <h3>What would you like to do next?</h3>
            <p>
                Choose if you have a discount code or reward points you want to use
                or would like to estimate your delivery cost.
            </p>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="total_area">
                    <ul>
                        <li>Tổng tiền: <span><?php echo Common::ViewMoney(GioHang::TongTien()); ?></span></li>
                        <li>Thuế: <span><?php echo Common::ViewMoney(GioHang::Thue()); ?></span></li>
                        <li>Phí giao hàng: <span><?php echo Common::ViewMoney(GioHang::PhiGiaoHang()); ?></span></li>
                        <li>Tạm tính: <span><?php echo Common::ViewMoney(GioHang::TamTinh()); ?></span></li>
                    </ul>
                    <a class="btn btn-default check_out" href="/cart/checkout/index/">
                        Đặt hàng
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/#do_action-->