<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/backend/">Trang Chủ</a></li>
    <li class="breadcrumb-item"><a href="/backend/pages">Trang</a></li>
    <li class="breadcrumb-item active">Sửa</li>
</ol>
<section class="content">
    <div class="card card-primary ">
        <div class="card-header">
            <h4 class="card-title">
                Sửa Trang
            </h4>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="card-body">
                <?php

                use Model\Pages;
                use Model\Pages\PagesForm;

                $formPages = new PagesForm();

                $pagesDetail = new Pages($_Params[0]);

                $formPages->Id($pagesDetail->Id)->render();
                ?>
                <div class="row">
                    <div class="col-12">
                        <?php $formPages->Name($pagesDetail->Name)->renderHtml();  ?>
                        <?php $formPages->Alias($pagesDetail->Alias)->renderHtml();  ?>
                    </div>
                    <div class="col-4">
                        <?php $formPages->Keyword($pagesDetail->Keyword)->renderHtml();  ?>
                    </div>
                    <div class="col-4">
                        <?php $formPages->Des($pagesDetail->Des)->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formPages->Lang($pagesDetail->Lang)->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formPages->isDelete($pagesDetail->isDelete)->renderHtml();  ?>
                    </div>
                </div>
                <?php
                $formPages->Content($pagesDetail->Content())->renderHtml();
                $formPages->Images($pagesDetail->Images)->renderHtml();
                ?>
                <input onclick="BrowseServer('Images:/', 'Select_Images_Server')" type="button" id="btnChonFile" value="Chọn Hình">
                <img style="width: 100px;height: 100px;" src="<?php echo $pagesDetail->Images; ?>" alt="">
            </div>
            <div class="card-footer">
                <button class="btn btn-success">Sửa</button>
            </div>
        </form>
    </div>
</section>