 <section class="content-header">
     <div class="container-fluid">
         <div class="row mb-2">
             <div class="col-sm-6">
                 <h1>Cài Đặt Mail</h1>
             </div>
             <div class="col-sm-6">
                 <ol class="breadcrumb float-sm-right">
                     <li class="breadcrumb-item"><a href="/backend">Trang chủ</a></li>
                     <li class="breadcrumb-item active">Cài Đặt Mail</li>
                 </ol>
             </div>
         </div>
     </div><!-- /.container-fluid -->
 </section>
 <!-- Main content -->
 <section class="content">
     <?php
        $file = "public\Maincontent\Mainchangepassword.html";
        $content = file_get_contents($file);
        if (isset($_POST["mailContent"])) {
            $contentPost = $_POST["mailContent"];
            file_put_contents($file, $contentPost);
        }
        $content = file_get_contents($file);
        ?>
     <form action="" method="post">
         <textarea class="editor" name="mailContent" id="content"><?php echo $content ?></textarea>
         <button class="btn btn-success">Lưu</button>
     </form>
 </section>
 <!-- /.content -->