<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/backend/">Trang Chủ</a></li>
    <li class="breadcrumb-item"><a href="/backend/options">Tùy Chọn</a></li>
    <li class="breadcrumb-item active">Tạo mới</li>
</ol>
<section class="content">
    <div class="card card-primary ">
        <div class="card-header">
            <h4 class="card-title">
                Thêm Tùy Chọn
            </h4>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="card-body">
                <?php

                use Model\Options\OptionsForm;

                $formTable = new OptionsForm();
                // $formTable->Id()->render();
                ?>
                <div class="">
                    <div class="col-6">
                        <?php $formTable->Code()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->Name()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->Description()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->GroupName()->renderHtml();  ?>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-success">Thêm</button>
            </div>
        </form>
    </div>

</section>