<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/backend/">Trang Chủ</a></li>
    <li class="breadcrumb-item"><a href="/backend/menu">Menu</a></li>
    <li class="breadcrumb-item active">Sửa</li>
</ol>
<!-- /backend/menu/post/MenuTopHeader -->
<section class="content">
    <div class="card card-primary ">
        <div class="card-header">
            <h4 class="card-title">
                Sửa Menu
            </h4>
        </div>

        <form action="" method="post" enctype="multipart/form-data">
            <div class="card-body">
                <?php

                use Model\Menu;

                $id =  $_Params[0] ?? "";
                $menu = new Menu($id);
                $nameMenu = $menu->GroupName;

                use Model\Menu\MenuForm;

                $formTable = new MenuForm();
                // $formTable->Id()->render();
                ?>
                <div class="">
                    <div class="col-6">
                        <?php $formTable->Id($menu->Id)->render();  ?>
                        <?php $formTable->Name($menu->Name)->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->Link($menu->Link)->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->STT($menu->STT)->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->Icon($menu->Icon)->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->GroupName($nameMenu)->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formTable->CapCha($nameMenu)->renderHtml();  ?>
                    </div>

                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-success">Sửa</button>
            </div>
        </form>
    </div>

</section>
<script>
    $(function() {
        $("#SelectGroupName").change(function() {
            //alert($(this).val());
            window.location.href = `/backend/menu/post/${$(this).val()}`;
        });
    });
</script>