<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h1>Bảo mật</h1>
        <form action="" method="post">

            <?php

            use Model\Error;
            use Model\Users\UsersPassword;

            $error = Error::get();
            if ($error != null) {
            ?>
                <div class="alert alert-<?php echo $error->type; ?>">
                    <?php echo $error->content; ?>
                </div>
            <?php
            }
            $FormPass = new UsersPassword();
            $FormPass->password()->renderHTML();
            $FormPass->newpassword()->renderHTML();
            $FormPass->repassword()->renderHTML();
            ?>
            <button class="btn btn-success" type="submit">Lưu</button>
        </form>
    </div>

</div>