<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản lý đặt hàng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Quản lý đặt hàng</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="container">
    <div class="card text-left">
        <img class="card-img-top" src="holder.js/100px180/" alt="">
        <div class="card-body">
            <p class="card-text">
                <a href="/cart/cartmanage/pages" class="btn-lg btn btn-primary">
                    Trang Đặt Hàng Thành Công
                </a>
                <a href="/cart/cartmanage/danhsachdonhang" class="btn btn-lg btn-primary">
                    Danh Sách Đơn Hàng
                </a>
                <a href="/cart/cartmanage/sanpham" class="btn btn-lg btn-primary">
                    Danh Sách Sản phẩm đặt hàng
                </a>
            </p>
        </div>
    </div>
</div>