 <?php

use Model\Admin;
// thong tin cua tai khoan dang dang nhap
 $user = new Admin(Admin::CurentUser());

 ?>


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thông tin cá nhân</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Thông tin cá nhân</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <form action="" method="POST">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Thông tin cá nhân</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="">Họ & Tên</label>
                    <input value="<?php echo $user->Fullname; ?>" type="text" name="user[HoTen]" class="form-control" placeholder="Họ & Tên" aria-describedby="helpId">
                </div>
                <div class="form-group">
                    <label for="">SĐT</label>
                    <input value="<?php echo $user->Phone; ?>" type="text" name="user[SDT]" class="form-control" placeholder="SĐT" aria-describedby="helpId">
                </div>
                <div class="form-group">
                    <label for="">Email</label>
                    <input value="<?php echo $user->Email; ?>" type="text" name="user[Email]" class="form-control" placeholder="Email" aria-describedby="helpId">
                </div>
                <div class="form-group">
                    <label for="">Địa Chỉ</label>
                    <input value="<?php echo $user->Address; ?>" type="text" name="user[DiaChi]" class="form-control" placeholder="Địa Chỉ" aria-describedby="helpId">
                </div>
                <div class="row">
                    <div class="col-4 form-group">
                        <label for="">Tỉnh</label>
                        <select data-value="<?php echo $user->Province ?>" id="tinhThanh" name="user[Tinh]" class="form-control"> </select>
                    </div>
                    <div class="col-4 form-group">
                        <label for="">Huyện</label>
                        <select data-value="<?php echo $user->District ?>" id="quanHuyen" name="user[Huyen]" class="form-control"> </select>

                    </div>
                    <div class="col-4 form-group">
                        <label for="">Xã</label>
                        <select data-value="<?php echo $user->Ward ?>" id="phuongXa" name="user[Xa]" class="form-control"> </select>
                    </div>
                </div>

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <!-- Footer -->
                <button name="btnLuu" class="btn btn-success">
                    Lưu
                </button>
                <button type="reset" class="btn btn-default">
                    Làm lại
                </button>
            </div>
            <!-- /.card-footer-->
        </div>
    </form> 
</section>
<!-- /.content -->
<script src="/public/TinhThanh/tinhthanh.js" ></script>