<ol class="breadcrumb">
       <li class="breadcrumb-item"><a href="/backend/">Trang Chủ</a></li>
       <li class="breadcrumb-item"><a href="/backend/danhmuc">Danh Mục</a></li>
       <li class="breadcrumb-item active">Tạo mới</li>
   </ol> 
<section class="content">
    <div class="card card-primary " >
        <div class="card-header">
            <h4 class="card-title">
                Thêm Danh Mục
            </h4>
        </div>
        <form action="" method="post">
            <div class="card-body">
                <div class="form-group">
                  <label >Mã</label>
                  <input type="text" class="form-control" name="Id" placeholder=""> 
                </div>
                <div class="form-group">
                  <label >Tên Danh Mục</label>
                  <input type="text" class="form-control" name="Name" placeholder=""> 
                </div>
                <div class="form-group">
                  <label >Mô Tả</label>
                  <textarea type="text" rows="10" class="form-control" name="Decription" placeholder="Mô Tả"></textarea> 
                </div>
                <div class="form-group">
                  <label >
                  <input type="checkbox"  name="IsDelete" placeholder=""> 
                      Ẩn/Hiện 
                  </label>
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-success" >Thêm</button>
            </div>
        </form>

    </div>
     

</section>