<?php

use Model\DanhMuc;

// var_dump($data["DanhMuc"]);
$_danhMuc = new DanhMuc($data["DanhMuc"]);
// echo $_Controller;
// echo $_Action;
// echo $_Module;
?>
<ol class="breadcrumb">
       <li class="breadcrumb-item"><a href="/backend/">Trang Chủ</a></li>
       <li class="breadcrumb-item"><a href="/backend/danhmuc">Danh Mục</a></li>
       <li class="breadcrumb-item active">Cập Nhật</li>
</ol> 
<section class="content">
    <div class="card card-primary " >
        <div class="card-header">
            <h4 class="card-title">
                Sửa Danh Mục
            </h4>
        </div>
        <form action="" method="post">
            <div class="card-body">
                <div class="form-group">
                  <label >Mã</label>
                  <input readonly value="<?php echo $_danhMuc->Id; ?>" type="text" class="form-control" name="Id" placeholder=""> 
                </div>
                <div class="form-group">
                  <label >Tên Danh Mục</label>
                  <input value="<?php echo $_danhMuc->Name; ?>" type="text" class="form-control" name="Name" placeholder=""> 
                </div>
                <div class="form-group">
                  <label >Mô Tả</label>
                  <textarea type="text" rows="10" class="form-control" name="Decription" placeholder="Mô Tả"><?php echo $_danhMuc->Decription; ?></textarea> 
                </div>
                <div class="form-group">
                  <label >
                  <input <?php echo $_danhMuc->IsDelete == "1" ? 'checked' : ''; ?>  type="checkbox"  name="IsDelete" placeholder=""> 
                      Ẩn/Hiện 
                  </label>
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-success" >Sửa</button>
            </div>
        </form>
    
    </div>
     

</section>