<section id="form">
    <!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="login-form">
                    <!--login form-->
                    <h2>Đăng Nhập</h2>
                    <form action="" method="post">
                        <input type="text" name="username" placeholder="tài khoản" />
                        <input type="password" name="password" placeholder="mật khẩu" />
                        <span>
                            <input name="isLogin" type="checkbox" class="checkbox" />
                            giữ đăng nhập
                        </span>
                        <button type="submit" class="btn btn-default">Đăng nhập</button>
                    </form>
                </div>
                <!--/login form-->
            </div>
            <div class="col-sm-1">
                <h2 class="or">hoặc</h2>
            </div>
            <div class="col-sm-4">
                <div class="signup-form">
                    <!--sign up form-->
                    <h2>Tạo tài khoản!</h2>
                    <form action="#">
                        <input autocomplete="off" type="text" placeholder="tài khoản" />
                        <input autocomplete="off" type="email" placeholder="Email" />
                        <input autocomplete="off" type="password" placeholder="Mật khẩu" />
                        <input autocomplete="off" type="password" placeholder="Nhập lại mật khẩu" />
                        <button type="submit" class="btn btn-default">Đăng Ký</button>
                    </form>
                </div>
                <!--/sign up form-->
            </div>
        </div>
    </div>
</section>