<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/backend/">Trang Chủ</a></li>
    <li class="breadcrumb-item"><a href="/backend/danhmuc">Sản Phẩm</a></li>
    <li class="breadcrumb-item active">Tạo mới</li>
</ol>
<section class="content">
    <div class="card card-primary ">
        <div class="card-header">
            <h4 class="card-title">
                Thêm Sản Phẩm
            </h4>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="card-body">
                <?php

                use Model\SanPhamForm;

                $formSanPham = new SanPhamForm();
                // $formSanPham->Id()->render();
                ?>
                <div class="row">
                    <div class="col-6">
                        <?php $formSanPham->Code()->renderHtml();  ?>
                    </div>
                    <div class="col-6">
                        <?php $formSanPham->Name()->renderHtml();  ?>
                    </div>
                    <div class="col-4">
                        <?php $formSanPham->Price()->renderHtml(); ?>
                    </div>
                    <div class="col-4">
                        <?php $formSanPham->SalePrice()->renderHtml();  ?>
                    </div>
                    <div class="col-4">
                        <?php $formSanPham->IdDM(1)->renderHtml(); ?>
                    </div>
                    <div class="col-4">
                        <?php $formSanPham->Keyword()->renderHtml();  ?>
                    </div>
                    <div class="col-4">
                        <?php $formSanPham->Decription()->renderHtml();  ?>
                    </div>
                    <div class="col-4">
                        <?php $formSanPham->Title()->renderHtml(); ?>
                    </div>

                </div>
                <?php
                $formSanPham->Content()->renderHtml();
                $formSanPham->UrlImages()->renderHtml();
                $formSanPham->Active()->renderHtml();

                ?>
            </div>
            <div class="card-footer">
                <button class="btn btn-success">Thêm</button>
            </div>
        </form>

    </div>


</section>