<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/backend/">Trang Chủ</a></li>
    <li class="breadcrumb-item"><a href="/backend/danhmuc">Sản Phẩm</a></li>
    <li class="breadcrumb-item active">Tạo mới</li>
</ol>
<section class="content">
    <div class="card card-primary ">
        <div class="card-header">
            <h4 class="card-title">
                Thêm Sản Phẩm
            </h4>
        </div>
        <form action="" method="post">
            <div class="card-body">
                <?php

                use Model\SanPhamForm;

                $formSanPham = new SanPhamForm();
                $formSanPham->Id()->render();
                $formSanPham->Code()->renderHtml();
                $formSanPham->Price()->renderHtml();
                $formSanPham->SalePrice()->renderHtml();
                $formSanPham->IdDM(1)->renderHtml();
                $formSanPham->Keyword()->renderHtml();
                $formSanPham->Decription()->renderHtml();
                $formSanPham->Title()->renderHtml();
                $formSanPham->Content()->renderHtml();
                $formSanPham->UrlImages()->renderHtml();
                $formSanPham->Active()->renderHtml();

                ?>
            </div>
            <div class="card-footer">
                <button class="btn btn-success">Thêm</button>
            </div>
        </form>

    </div>


</section>